from tkinter import *
# Main window
root = Tk()
root.title("Calculator")
root.geometry("300x400")
# Entry widget
entry = Entry(root, font=('Arial', 24), width=18, borderwidth=5, relief=RIDGE, justify=RIGHT)
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=10)
# Button layout and commands using lambda (no separate functions)
Button(root, text='7', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '7')).grid(row=1, column=0)
Button(root, text='8', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '8')).grid(row=1, column=1)
Button(root, text='9', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '9')).grid(row=1, column=2)
Button(root, text='/', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '/')).grid(row=1, column=3)
Button(root, text='4', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '4')).grid(row=2, column=0)
Button(root, text='5', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '5')).grid(row=2, column=1)
Button(root, text='6', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '6')).grid(row=2, column=2)
Button(root, text='*', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '*')).grid(row=2, column=3)
Button(root, text='1', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '1')).grid(row=3, column=0)
Button(root, text='2', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '2')).grid(row=3, column=1)
Button(root, text='3', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '3')).grid(row=3, column=2)
Button(root, text='-', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '-')).grid(row=3, column=3)
Button(root, text='0', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '0')).grid(row=4, column=0)
Button(root, text='.', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '.')).grid(row=4, column=1)
Button(root, text='=', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, str(eval(entry.get())))).grid(row=4, column=2)
Button(root, text='+', width=5, height=2, font=('Arial', 14), command=lambda: entry.insert(END, '+')).grid(row=4, column=3)
Button(root, text='C', width=22, height=2, font=('Arial', 14), command=lambda: entry.delete(0, END)).grid(row=5, column=0, columnspan=4)
root.mainloop()
