#Write a Python Program to create a Mobile Class and Perform Instantiation for 10 Objects
class Mobile:
    def __init__(self):
        print("i have created")
m1=Mobile()
print(type(m1))
print(id(m1))
m2=Mobile()
print(type(m2))
print(id(m2))
m3=Mobile()
print(type(m3))
print(id(m3))
m4=Mobile()
print(type(m4))
print(id(m4))
m5=Mobile()
print(type(m5))
print(id(m5))
m6=Mobile()
print(type(m6))
print(id(m6))
m7=Mobile()
print(type(m7))
print(id(m7))
m8=Mobile()
print(type(m8))
print(id(m8))
m9=Mobile()
print(type(m9))
print(id(m9))
m10=Mobile()
print(type(m10))
print(id(m10))